### PR TITLE
Introduce Command Palette section and more Projects articles

### PR DESCRIPTION
**Pull request by parisk**
Introduce the following articles:

- Command Palette / About the Command Palette
- Projects / The Public URL
- Projects / Deleting a project
- Projects / Downloading files from the web to my project

### CODE REVIEW

**Comment by mkarajohn** [comment]
Articles look ok, except for [this](http://6siddqtg.apps.lair.io/projects/download-files-from-your-project-to-your-desktop/) which is missing an image

**Comment by parisk** [comment]
The reported article is from a previous PR. What is the title of the article you are talking about?

**Comment by mkarajohn** [comment]
Oh, sorry, mixed up the titles and looked at the wrong one :sweat_smile:

**Comment by parisk** [comment]
No prob. So is this LGTM from you?

**Comment by mkarajohn** [comment]
Yep, :sheep:

**Pull request merged**
